# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Davide Prati
email: your-email@domain.com
math: your-email@domain.com
description_header: visual artist and interactive developer based in Berlin.
description: > # this means to ignore newlines until "baseurl:"
  Iâ€™m interested in how the natural processes that give shape to water, terrains, trees, mountains and clouds are applicable to design, visual art, websites, videogames and interactive installations.
description_contact: I like hearing about possible new work. Get in touch
description_metatag: > # this means to ignore newlines until "baseurl:"
  visual artist and interactive developer based in Berlin. Computer graphics (WebGL, openFrameworks, Processing,
shaders), computer vision, prototyping.
description_contact: I like hearing about possible new work. Get in touch
baseurl: "" # the subpath of your site, e.g. /blog
url: "http://davideprati.com" # the base hostname & protocol for your site
twitter_username: edapx
github_username:  edap
exclude: ['*/node_modules', 'shaders']
collections:
  projects:
    cover: ""
    cover_vimeo: ""
    output: true
# Build settings
markdown: kramdown
incremental: true
